<a href="https://colab.research.google.com/github/Msaleemakhtar/Deep-Learning-with-pytorch/blob/main/00_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Deep Learning with Pytorch**

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



# ***Tensors in pytorch***

In [ ]:
# scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
scalar.item()

4

In [ ]:
vec = torch.tensor([1,2,3,4])

In [ ]:
vec.ndim


1

In [ ]:
vec.shape

torch.Size([4])

In [ ]:
Mat = torch.tensor([
    [1,2,3,4],
    [2,4,6,7],
    [6,7,8,9]
])

In [ ]:
Mat.shape

torch.Size([3, 4])

In [ ]:
Mat.ndim

2

In [ ]:
My_tensor = torch.tensor(
    [[[1,2,3,4],
    [2,4,6,7],
    [6,7,8,9]],

    [[11,21,31,41],
    [21,41,61,17],
    [16,71,81,19]]]


    )

In [ ]:
My_tensor.shape

torch.Size([2, 3, 4])

In [ ]:

tensor_4d = torch.tensor(
  [[[[1,2,3,4],
    [2,4,6,7],
    [6,7,8,9]],

    [[11,21,31,41],
    [21,41,61,17],
    [16,71,81,19]]]]


    )

In [ ]:
tensor_4d.ndim

4

In [ ]:

tensor_4d.shape

torch.Size([1, 2, 3, 4])

In [ ]:
random_tensor = torch.rand(size=(1,2,5))

In [ ]:
random_tensor.shape

torch.Size([1, 2, 5])

In [ ]:
random_tensor

tensor([[[0.6726, 0.7824, 0.0259, 0.3573, 0.3561],
         [0.6247, 0.0661, 0.7991, 0.4381, 0.4266]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
zero_tensor = torch.zeros(2,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
one_tensor = torch.ones(2,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zero_10_tensor = torch.arange(start=0,end=10,step=2)
zero_10_tensor

tensor([0, 2, 4, 6, 8])

In [ ]:
zero_like_tensor = torch.zeros_like(input=zero_10_tensor)
zero_like_tensor

tensor([0, 0, 0, 0, 0])

In [ ]:
ones_like_tensor = torch.ones_like(input=zero_10_tensor)
ones_like_tensor

tensor([1, 1, 1, 1, 1])

In [ ]:
p = torch.tensor([1.0,2.3,4.0],dtype=None, requires_grad=False, device= None )
print(p)
print(p.dtype)
print(p.requires_grad)
print(p.device)
print(p.shape)


tensor([1.0000, 2.3000, 4.0000])
torch.float32
False
cpu
torch.Size([3])


In [ ]:
p = torch.tensor([[1.0,2.3,4.0],[1.0,2.3,4.0]],dtype=torch.half, requires_grad=False, device= None )
print(p)
print(p.dtype)
print(p.requires_grad)
print(p.device)
print(p.shape)


tensor([[1.0000, 2.3008, 4.0000],
        [1.0000, 2.3008, 4.0000]], dtype=torch.float16)
torch.float16
False
cpu
torch.Size([2, 3])


In [ ]:
tens_add = torch.tensor([1,3,4,5])


In [ ]:
tens_add

tensor([1, 3, 4, 5])

In [ ]:
tens_add + 22

tensor([23, 25, 26, 27])

In [ ]:
tens_add * 2

tensor([ 2,  6,  8, 10])

In [ ]:
tens_add / 2

tensor([0.5000, 1.5000, 2.0000, 2.5000])

In [ ]:
tens_add.dtype

torch.int64

In [ ]:
y = torch.add(tens_add,2)

In [ ]:
y

tensor([3, 5, 6, 7])

In [ ]:
ml= torch.mul(tens_add,3)
ml

tensor([ 3,  9, 12, 15])

In [ ]:
tens_add[0] = 7


In [ ]:
tens_add / tens_add

tensor([1., 1., 1., 1.])

In [ ]:
# Matrix multiplication(dot product)
# Multiplication(elementwise)

MatMa= torch.tensor([1,3,4,5])
MatMa

tensor([1, 3, 4, 5])

In [ ]:

MatMa * 2

tensor([ 2,  6,  8, 10])

In [ ]:
%%time
MatMa * MatMa

CPU times: user 422 µs, sys: 0 ns, total: 422 µs
Wall time: 330 µs


tensor([ 1,  9, 16, 25])

In [ ]:
%%time

TEN = torch.matmul(MatMa , MatMa)

CPU times: user 105 µs, sys: 0 ns, total: 105 µs
Wall time: 108 µs


In [ ]:
TEN

tensor(51)

In [ ]:
import torch

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
torch.mean(x.type(torch.float)), x.type(torch.float).mean()


(tensor(45.), tensor(45.))

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
x[0]

tensor(0)

In [ ]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
x[9]

tensor(90)

In [ ]:
rshape = torch.arange(1,13)
rshape , rshape.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
c = rshape.reshape(2,6)
c

tensor([[ 6,  6,  6,  6,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [ ]:
c.dtype

torch.int64

In [ ]:
R = rshape.view(3,4)

In [ ]:
R

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
rshape

tensor([ 6,  6,  6,  6,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
R[0] = 6

In [ ]:
R

tensor([[ 6,  6,  6,  6],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
stack = torch.arange(1,5)

In [ ]:
stack

tensor([1, 2, 3, 4])

In [ ]:
torch.stack((stack,stack), dim=1)

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [ ]:
import torch

In [ ]:
X = torch.arange(1,19).reshape(2,3,3)
X

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
X[:1, :,0:2,
  ]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [ ]:
import numpy as np
import torch

arr = np.arange(1.0, 8.0)


In [ ]:
myarr = torch.from_numpy(arr)
myarr

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
arr2 = torch.arange(0.0,5.0)

In [ ]:
arr2.dtype

torch.float32

In [ ]:
tonmp = arr2.numpy()

In [ ]:
tonmp.dtype

dtype('float32')

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device



'cpu'